# Generated by Django 4.1.4 on 2022-12-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('size', models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('eXtra Large', 'XL')], max_length=30, verbose_name='Размер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('currency', models.CharField(choices=[('USD', 'DOLLAR'), ('KGS', 'SOM'), ('TENGE', 'TENGE')], default='kgz', max_length=100, verbose_name='Валюта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='ID-Категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='default', verbose_name='Заглавие')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('description', models.TextField(default='default', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('country_of_origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производства')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserCapsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Нравится')),
                ('favorites', models.BooleanField(default=False, verbose_name='Избранное')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Нормально'), (2, 'Хорошо'), (3, 'Отлично'), (4, 'Прекрасно'), (5, 'Изумительно')], null=True, verbose_name='Оценка')),
                ('caps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_caps.caps', verbose_name='Кепка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='caps',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_caps.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='caps',
            name='magazine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shops', to='custom_caps.magazine', verbose_name='Магазин'),
        ),
        migrations.AddField(
            model_name='caps',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shops', to='custom_caps.manufacturer', verbose_name='Производитель'),
        ),
    ]
